bkp/controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\Auth;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
use yii\bootstrap4\ActiveForm;
use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\UserPasswordResetRequestForm;
use app\models\UserResetPasswordForm;
use app\models\Users;
use app\widgets\Alert;
use yii\base\InvalidParamException;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;

class AuthController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['logout', 'password', 'profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['request-password-reset', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionIndex()
    {
        $this->layout = 'auth';

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/informe-rendimento']);
        }

        $model = new LoginForm();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/informe-rendimento']);
        }

        $model->password = '';
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Sair
     */
    public function actionLogout()
    {
        \Yii::$app->user->logout();
        return $this->redirect(['/auth/index']);
    }

    /**
     * Solicitar nova senha
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'auth';
        $model = new UserPasswordResetRequestForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->document) {
                $result = Yii::$app->webservice->getWebservice('collaborator', ['numCpf' => $model->document]);

                if (isset($result->TMCSColaboradores)) {
                    if (is_array($result->TMCSColaboradores)){
                        foreach ($result->TMCSColaboradores as $colaborador) {
                            if ($colaborador->sitAfa == 1) {
                                if ($colaborador->datNas == $model->birthDate && 
                                $colaborador->numCad == $model->codUser) {
                                    $user = Auth::findOne(['CD_COLABORADOR' => $model->codUser]);

                                    if ($user) {
                                        $user->DS_SENHA = $model->password;
                                        $user->save();
                                        Yii::$app->session->setFlash('success', 'Senha atualizada com sucesso. Você já pode autenticar com a nova senha!');
                                        return $this->redirect(['/auth']);
                                    } else {
                                        Yii::$app->session->setFlash('warning', 'Colaborador não encontrado no sistema da Intranet');
                                    }
                                } else {
                                    Yii::$app->session->setFlash('error', 'Não foi possível atualizar a sua senha, verifique seus dados e tente novamente!');
                                }
                            }
                        }
                    } elseif ($result->TMCSColaboradores->datNas == $model->birthDate && 
                    $result->TMCSColaboradores->numCad == $model->codUser) {

                        $user = Auth::findOne(['CD_COLABORADOR' => $model->codUser]);

                        if ($user) {
                            $user->DS_SENHA = $model->password;
                            $user->save();
                            Yii::$app->session->setFlash('success', 'Senha atualizada com sucesso. Você já pode autenticar com a nova senha!');
                            return $this->redirect(['/auth']);
                        } else {
                            Yii::$app->session->setFlash('warning', 'Colaborador não encontrado no sistema da Intranet');
                        }                    
                    } else {
                        Yii::$app->session->setFlash('error', 'Não foi possível atualizar a sua senha, verifique seus dados e tente novamente!');
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Não foi possível atualizar a sua senha, verifique seus dados e tente novamente!');
                }
            }
        }

        return $this->render('requestPasswordResetToken', ['model' => $model]);
    }
}

bkp/views/layouts/auth.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

// use Yii;
use app\widgets\Alert;
use yii\helpers\Url;
use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="<?= Url::to('@web/favicon.ico') ?>" type="image/x-icon">
  <link rel="icon" href="<?= Url::to('@web/favicon.ico') ?>" type="image/x-icon">
  <?php $this->registerCsrfMetaTags() ?>
  <title><?= Html::encode('Aker Solutions') ?></title>

  <!-- Assets --><?php $this->head() ?>
  <!-- PWA -->
  <!-- Web Application Manifest -->
  <link rel="manifest" href="<?= Url::to('@web/manifest.json') ?>">
  <!-- Chrome for Android theme color -->
  <meta name="theme-color" content="#038919">
  <!-- Add to homescreen for Chrome on Android -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="application-name" content="RENTAGRI">
  <link rel="icon" type="image/png" sizes="192x192" href="<?= Url::to('@web/android-icon-192x192.png') ?>">
  <link rel="icon" type="image/png" sizes="32x32" href="<?= Url::to('@web/favicon-32x32.png') ?>">
  <link rel="icon" type="image/png" sizes="96x96" href="<?= Url::to('@web/favicon-96x96.png') ?>">
  <link rel="icon" type="image/png" sizes="16x16" href="<?= Url::to('@web/favicon-16x16.png') ?>">
  <!-- Add to homescreen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="RENTAGRI">
  <link rel="apple-touch-icon" sizes="57x57" href="<?= Url::to('@web/apple-icon-57x57.png') ?>">
  <link rel="apple-touch-icon" sizes="60x60" href="<?= Url::to('@web/apple-icon-60x60.png') ?>">
  <link rel="apple-touch-icon" sizes="72x72" href="<?= Url::to('@web/apple-icon-72x72.png') ?>">
  <link rel="apple-touch-icon" sizes="76x76" href="<?= Url::to('@web/apple-icon-76x76.png') ?>">
  <link rel="apple-touch-icon" sizes="114x114" href="<?= Url::to('@web/apple-icon-114x114.png') ?>">
  <link rel="apple-touch-icon" sizes="120x120" href="<?= Url::to('@web/apple-icon-120x120.png') ?>">
  <link rel="apple-touch-icon" sizes="144x144" href="<?= Url::to('@web/apple-icon-144x144.png') ?>">
  <link rel="apple-touch-icon" sizes="152x152" href="<?= Url::to('@web/apple-icon-152x152.png') ?>">
  <link rel="apple-touch-icon" sizes="180x180" href="<?= Url::to('@web/apple-icon-180x180.png') ?>">
  <!-- Tile for Win8 -->
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="<?= Url::to('@web/ms-icon-144x144.png') ?>">
</head>

<body class="bg-white">
  <?php $this->beginBody() ?>
  <?= Alert::widget() ?>
  <main id="app" class="d-flex flex-column h-100 justify-content-center">
    <div class="py-5">
      <div class="container mb-4 text-center"> 
        <img src="<?= Url::to('@web/img/logo.png') ?>" class="img-fluid" width="500"/>
      </div>
      <?= $content ?>
    </div>
  </main>
  <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

bkp/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use app\components\ThumbHelper;
use app\assets\AppAsset;
use yii\bootstrap4\Breadcrumbs;
use app\models\Lead;
use yii\helpers\Url;

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <?= Html::csrfMetaTags() ?>
  <title><?= $this->title ? Html::encode($this->title . ' - ') : '' ?><?= Html::encode('Aker Solutions') ?></title>
  <?php $this->head() ?>
</head>

<body class="admin-panel">
  <?php $this->beginBody() ?>

    <?= Alert::widget() ?>
    
  <header class="store-header">
    <?php
    NavBar::begin([
      'brandLabel' => Html::img('@web/img/logo.png'),
      'brandUrl' => '',
      'options' => [
        'class' => 'navbar-expand-lg shadow-sm',
      ],
    ]); ?>
    <?php echo !Yii::$app->user->isGuest ? Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-nav-light ml-auto'],
        'encodeLabels' => false,
        'items' => [
            [
              'label' => 'HOLERITE',
              'url' => ['/holerite']
            ],
            [
              'label' => 'INFORME DE RENDIMENTOS',
              'url' => ['/informe-rendimento']
            ],
            [
              'label' => '|'
            ], 
            [
            'label' => 'Olá, ' . Yii::$app->user->identity->NM_USUARIO ?? 'Colaborador'
            ],        
            [
                'label' => 'Sair',
                'url' => ['/auth/logout'],
                'linkOptions' => [
                    'data-method' => 'post'
                ],
            
            ],
        ]
    ]) : '';
    NavBar::end();
    ?>
  </header>

  <div class="container mt-5 pb-5">
    <?= $content ?>
  </div>

  <?php $this->endBody() ?>
</body>

</html>

<?php ?>
<?php $this->endPage() ?>